name: Publish to npm

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  sailor:
    needs: tests
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: ./.github/workflows/publish-npm-public-pkg.yaml
    with:
      package-name: ${{ (github.event_name == 'workflow_dispatch' || github.ref_type == 'branch') && '@dev.sail.money/sailor' || '@sail.money/sailor' }}
      dist-tag: 'latest'
      build-number: ${{ (github.event_name == 'workflow_dispatch' || github.ref_type == 'branch') && github.run_number || 0 }}
    secrets: inherit
