name: Publish

on:
  push:
    tags: ['v*']
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  publish-npm:
    needs: tests
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: ./.github/workflows/publish-npm.yml
    with:
      environment: ${{ github.event_name == 'push' && github.ref_type == 'tag' && 'prod' || 'dev' }}
      version: ${{ github.ref_name }}
      skip-tests: true

  publish-github-packages:
    needs: tests
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: ./.github/workflows/publish-github-packages.yml
    with:
      environment: ${{ github.event_name == 'push' && github.ref_type == 'tag' && 'prod' || 'dev' }}
      version: ${{ github.ref_name }}
      skip-tests: true

  publish-docker:
    needs: tests
    permissions:
      contents: read
      id-token: write
      attestations: write
    uses: ./.github/workflows/publish-docker.yml
    with:
      environment: ${{ github.event_name == 'push' && github.ref_type == 'tag' && 'prod' || 'dev' }}
      version: ${{ github.ref_name }}
      skip-tests: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
